services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - ai-network
    environment:
      OLLAMA_CONTEXT_LENGTH: 64000
      OLLAMA_MAX_LOADED_MODELS: 2
      OLLAMA_NUM_PARALLEL: 1
    entrypoint: [ "/bin/sh", "-c" ]
    command:
      - |
        ollama serve &
        until ollama list > /dev/null 2>&1; do sleep 1; done

        for model in llama3.1:8b qwen2.5-coder:1.5b phi4:14b qwen3-embedding:0.6b; do
          ollama pull "$$model"
        done

        wait
0
volumes:
  ollama_data:

networks:
  ai-network:
    name: ai-network
